<?php

return [

  "vn" => [
    "urlDomain" => $folderName . '/',
    "databaseName" => "anhkiet_server",
    "text" => [
      "infoFooter" => "Thông tin công ty",
      "address" => "Địa chỉ",
      "phone" => "Số điện thoại",
      "email" => "Địa chỉ Email",
      "notFoundText" => "Trang không tồn tại !",
      "notFoundText2" => "Vui lòng quay lại",
      "notFoundText3" => "hoặc tìm kiếm bài viết khác !",
      "notFoundText4" => " Nếu có vấn đề gì xin quý khách vui lòng liên hệ quản trị !",

      'text1' => 'Tìm kiếm',
      'text2' => 'YÊU CẦU TƯ VẤN',
      'text3' => 'Xin vui lòng để lại địa chỉ email, chúng tôi sẽ cập nhật những tin tức quan trọng của',
      'text4' => 'tới quý khách',
      'text5' => 'Họ & Tên',
      'text6' => 'Số Điện Thoại',
      'text7' => 'BẤT ĐỘNG SẢN',
      'text8' => 'LIÊN KẾT',
      'text9' => 'Tổng đài CSKH',
      'text10' => 'Thông tin liên hệ',
      'text11' => 'Địa chỉ giao dịch:',
      'text12' => 'Điện thoại',
      'text13' => 'Thông báo',
      'text14' => 'Gửi tin nhắn tới chúng tôi',
      'text15' => 'Vui lòng điền đầy đủ thông tin theo yêu cầu để chúng tôi có thể hỗ trợ quý khách tốt nhất',
      'text17' => 'Tin nhắn',
      'text18' => 'Tôi cần...',
      'text19' => 'Gửi',
      'text20' => 'Cuộn xuống',
      'text21' => 'Bạn đang tìm kiếm thông tin tại',
      'text22' => 'Bất động sản bán',
      'text23' => 'Bất động sản cho thuê',
      'text24' => 'BĐS bán hot',
      'text25' => 'Xem toàn bộ',
      'text26' => 'BĐS cho thuê hot',
      'text27' => 'Tin tức',
      'text28' => 'Nơi hạnh phúc ngập tràn',
      'text29' => 'Cùng chuyên mục',
      'text30' => 'Nổi bật',
      'text31' => 'Bạn muốn sở hữu Căn hộ tại',
      'text32' => 'Liên hệ ngay',
      'text33' => 'Để nhận được tư vấn nhanh nhất',
      'text34' => 'Bạn muốn tìm kiếm ngôi nhà mơ ước ở đâu?',
      'text35' => 'Tìm kiếm dự án Bất động sản',
      'text36' => 'trên toàn quốc',
      'text37' => 'Chọn dòng sản phẩm',
      'text38' => 'Xem thêm',
      'text39' => 'Tìm kiếm dự án Bất động sản',
      'text40' => 'Có tất cả',
      'text41' => 'dự án phù hợp với kết quả tìm kiếm.',
      'text42' => 'Có thể bạn quan tâm',
    ]
  ],
  "en" => [
    "urlDomain" => $folderName . '/',
    "databaseName" => "anhkiet_reactjs",
    "text" => [
      "infoFooter" => "Information",
      "address" => "Address",
      "phone" => "Phone",
      "email" => "Email",
      "notFoundText" => "This page does not exist!",
      "notFoundText2" => "Please go back to the",
      "notFoundText3" => "or search for another article!",
      "notFoundText4" => "If you have any problems please contact the administrator.",

      'text1' => 'Search',
      'text2' => 'ASK FOR ADVICE',
      'text3' => 'Please leave your email address, we will update the important news of',
      'text4' => 'to you',
      'text5' => 'Full Name',
      'text6' => 'Phone',
      'text7' => 'REAL ESTATE',
      'text8' => 'LINK',
      'text9' => 'Customer Care Center',
      'text10' => 'Contact information',
      'text11' => 'Trading address:',
      'text12' => 'Phone',
      'text13' => 'Notification',
      'text14' => 'Send message to us',
      'text15' => 'Please fill in the information as required so we can best assist you',
      'text17' => 'Message',
      'text18' => 'I need...',
      'text19' => 'Send',
      'text20' => 'Scroll down',
      'text21' => 'You are looking for information at',
      'text22' => 'Real estate for sale',
      'text23' => 'Real estate for rent',
      'text24' => 'Hot sale real estate',
      'text25' => 'See all',
      'text26' => 'Hot property for rent',
      'text27' => 'News',
      'text28' => 'Where happiness is overwhelming',
      'text29' => 'The same category',
      'text30' => 'Highlights',
      'text31' => 'You want to own Apartments at',
      'text32' => 'Contact now',
      'text33' => 'To receive the fastest advice',
      'text34' => 'Where do you want to look for your dream home?',
      'text35' => 'Search real estate projects',
      'text36' => 'nationwide',
      'text37' => 'Select a product line',
      'text38' => 'See more',
      'text39' => 'Search real estate projects',
      'text40' => 'Have everything',
      'text41' => 'The project matches search results.',
      'text42' => 'Maybe you are interested',
    ]
  ]

];
